export default function tokenScope() {
  const basicScope = [
    "ITEMS_READ",
    "ITEMS_WRITE",
    "APPOINTMENTS_READ",
    "APPOINTMENTS_WRITE",
    "APPOINTMENTS_ALL_READ",
    "APPOINTMENTS_BUSINESS_SETTINGS_READ",
    "MERCHANT_PROFILE_READ",
    "MERCHANT_PROFILE_WRITE",
    "EMPLOYEES_WRITE",
    "EMPLOYEES_READ",
    "CUSTOMERS_READ",
    "CUSTOMERS_WRITE",
  ];
  const premiumScope = [
    "ITEMS_READ",
    "ITEMS_WRITE",
    "APPOINTMENTS_READ",
    "APPOINTMENTS_WRITE",
    "APPOINTMENTS_ALL_WRITE",
    "APPOINTMENTS_ALL_READ",
    "APPOINTMENTS_BUSINESS_SETTINGS_READ",
    "MERCHANT_PROFILE_READ",
    "MERCHANT_PROFILE_WRITE",
    "EMPLOYEES_WRITE",
    "EMPLOYEES_READ",
    "CUSTOMERS_READ",
    "CUSTOMERS_WRITE",
  ];

  const basicScopeString =
    "APPOINTMENTS_READ+APPOINTMENTS_WRITE+CUSTOMERS_WRITE+APPOINTMENTS_ALL_READ+CUSTOMERS_READ+APPOINTMENTS_BUSINESS_SETTINGS_READ+ITEMS_READ+ITEMS_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+EMPLOYEES_WRITE+EMPLOYEES_READ";

  const premiumScopeString =
    "APPOINTMENTS_READ+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+CUSTOMERS_WRITE+APPOINTMENTS_ALL_READ+CUSTOMERS_READ+APPOINTMENTS_BUSINESS_SETTINGS_READ+ITEMS_READ+ITEMS_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+EMPLOYEES_WRITE+EMPLOYEES_READ";

  return { premiumScope, basicScope, basicScopeString, premiumScopeString };
}
